// Generated by create_metadata.py. Do not edit manually.
export interface Project {
  id: number;
  title: string;
  cat: string;
  slug: string;
  side: "L" | "R";
  heroImage: string;
  gallery: string[];
  images: string[];
  location: string;
  year: string;
  area: string;
  status: string;
  isComingSoon?: boolean;
}

export const PROJECTS_DATA: Project[] = [
  {
    "id": 1,
    "title": "Parnaka Residency",
    "cat": "Residential",
    "slug": "parnaka-residency",
    "side": "L",
    "heroImage": "/project photos/photos and video/Parnaka/1.jpg",
    "gallery": [
      "/project photos/photos and video/Parnaka/10.jpg",
      "/project photos/photos and video/Parnaka/2.jpg"
    ],
    "images": [
      "/project photos/photos and video/Parnaka/1.jpg",
      "/project photos/photos and video/Parnaka/10.jpg",
      "/project photos/photos and video/Parnaka/2.jpg",
      "/project photos/photos and video/Parnaka/3.jpg",
      "/project photos/photos and video/Parnaka/4.jpg",
      "/project photos/photos and video/Parnaka/5.jpg",
      "/project photos/photos and video/Parnaka/6.jpg",
      "/project photos/photos and video/Parnaka/7.jpg",
      "/project photos/photos and video/Parnaka/8.jpg",
      "/project photos/photos and video/Parnaka/9.jpg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.05.14.jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.16.51 (1).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.16.51 (2).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.16.51.jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.01 (1).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.01.jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.28 (1).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.28 (2).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.28.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 2,
    "title": "Chandresh Palace",
    "cat": "Residential",
    "slug": "chandresh-palace",
    "side": "R",
    "heroImage": "/project photos/photos and video/chandresh /1.jpg",
    "gallery": [
      "/project photos/photos and video/chandresh /3.jpg",
      "/project photos/photos and video/chandresh /6.jpg"
    ],
    "images": [
      "/project photos/photos and video/chandresh /1.jpg",
      "/project photos/photos and video/chandresh /3.jpg",
      "/project photos/photos and video/chandresh /6.jpg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 3,
    "title": "Arunoday Complex",
    "cat": "Residential",
    "slug": "arunoday-complex",
    "side": "L",
    "heroImage": "/project photos/photos and video/Arunoday/arunoday 1/1.jpg",
    "gallery": [
      "/project photos/photos and video/Arunoday/arunoday 1/2.jpg",
      "/project photos/photos and video/Arunoday/arunoday 1/Scene 179(1).png"
    ],
    "images": [
      "/project photos/photos and video/Arunoday/arunoday 1/1.jpg",
      "/project photos/photos and video/Arunoday/arunoday 1/2.jpg",
      "/project photos/photos and video/Arunoday/arunoday 1/Scene 179(1).png"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 4,
    "title": "Gurudarshan Residency",
    "cat": "Residential",
    "slug": "gurudarshan-residency",
    "side": "R",
    "heroImage": "/project photos/photos and video/Gurudarshan/guru/1.jpg",
    "gallery": [
      "/project photos/photos and video/Gurudarshan/guru/2.jpg",
      "/project photos/photos and video/Gurudarshan/guru/3.jpg"
    ],
    "images": [
      "/project photos/photos and video/Gurudarshan/guru/1.jpg",
      "/project photos/photos and video/Gurudarshan/guru/2.jpg",
      "/project photos/photos and video/Gurudarshan/guru/3.jpg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 5,
    "title": "Lodha Veer Savarkar",
    "cat": "Residential",
    "slug": "lodha-veer-savarkar",
    "side": "L",
    "heroImage": "/project photos/photos and video/Lodha veer savarkar/LEFT SIDE VIEW.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/Lodha veer savarkar/RIGHT SIDE VIEW .jpg.jpeg",
      "/project photos/photos and video/Lodha veer savarkar/WORM VIEW.jpg.jpeg",
      "/project photos/photos and video/Lodha veer savarkar/bird eye view.jpg (2).jpeg"
    ],
    "images": [
      "/project photos/photos and video/Lodha veer savarkar/LEFT SIDE VIEW.jpg.jpeg",
      "/project photos/photos and video/Lodha veer savarkar/RIGHT SIDE VIEW .jpg.jpeg",
      "/project photos/photos and video/Lodha veer savarkar/WORM VIEW.jpg.jpeg",
      "/project photos/photos and video/Lodha veer savarkar/bird eye view.jpg (2).jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 6,
    "title": "Satyasaurabh Heights",
    "cat": "Residential",
    "slug": "satyasaurabh-heights",
    "side": "R",
    "heroImage": "/project photos/photos and video/Satyasaurabh/6260c905-0763-4179-9ec7-a18cc67500f6.jpg",
    "gallery": [
      "/project photos/photos and video/Satyasaurabh/79152f2d-834f-4d5a-8782-7b97975a276b.jpg",
      "/project photos/photos and video/Satyasaurabh/d09d2f72-2fc3-4a85-9a6a-2044eb3079dc.jpg"
    ],
    "images": [
      "/project photos/photos and video/Satyasaurabh/6260c905-0763-4179-9ec7-a18cc67500f6.jpg",
      "/project photos/photos and video/Satyasaurabh/79152f2d-834f-4d5a-8782-7b97975a276b.jpg",
      "/project photos/photos and video/Satyasaurabh/d09d2f72-2fc3-4a85-9a6a-2044eb3079dc.jpg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 7,
    "title": "Cheda Girnar",
    "cat": "Residential",
    "slug": "cheda-girnar",
    "side": "L",
    "heroImage": "/project photos/photos and video/cheda girnar/1.jpeg",
    "gallery": [
      "/project photos/photos and video/cheda girnar/2.jpeg",
      "/project photos/photos and video/cheda girnar/3.jpeg"
    ],
    "images": [
      "/project photos/photos and video/cheda girnar/1.jpeg",
      "/project photos/photos and video/cheda girnar/2.jpeg",
      "/project photos/photos and video/cheda girnar/3.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 8,
    "title": "Happy Villa",
    "cat": "Residential",
    "slug": "happy-villa",
    "side": "R",
    "heroImage": "/project photos/photos and video/happy villa/Bird Eye View A.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/happy villa/DAY CAM 01.jpg.jpeg",
      "/project photos/photos and video/happy villa/EVE.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/happy villa/Bird Eye View A.jpg.jpeg",
      "/project photos/photos and video/happy villa/DAY CAM 01.jpg.jpeg",
      "/project photos/photos and video/happy villa/EVE.jpg.jpeg",
      "/project photos/photos and video/happy villa/draft 03.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 9,
    "title": "IDBI Commercial Hub",
    "cat": "Commercial",
    "slug": "idbi-commercial-hub",
    "side": "L",
    "heroImage": "/project photos/photos and video/idbi/Bird Eye View.jpg (1).jpeg",
    "gallery": [
      "/project photos/photos and video/idbi/Night View 02_A.jpg.jpeg",
      "/project photos/photos and video/idbi/Night View.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/idbi/Bird Eye View.jpg (1).jpeg",
      "/project photos/photos and video/idbi/Night View 02_A.jpg.jpeg",
      "/project photos/photos and video/idbi/Night View.jpg.jpeg",
      "/project photos/photos and video/idbi/idbi day.jpg.jpeg",
      "/project photos/photos and video/idbi/worm eye view render copy.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 10,
    "title": "Karari Heights",
    "cat": "Residential",
    "slug": "karari-heights",
    "side": "R",
    "heroImage": "/project photos/photos and video/karari heights (Yamuna Satkar)/Day_01_1.jpg (1).jpeg",
    "gallery": [
      "/project photos/photos and video/karari heights (Yamuna Satkar)/Night View_2.jpg.jpeg",
      "/project photos/photos and video/karari heights (Yamuna Satkar)/Saraunding view 02_1.jpg.jpeg",
      "/project photos/photos and video/karari heights (Yamuna Satkar)/worm01_2.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/karari heights (Yamuna Satkar)/Day_01_1.jpg (1).jpeg",
      "/project photos/photos and video/karari heights (Yamuna Satkar)/Night View_2.jpg.jpeg",
      "/project photos/photos and video/karari heights (Yamuna Satkar)/Saraunding view 02_1.jpg.jpeg",
      "/project photos/photos and video/karari heights (Yamuna Satkar)/worm01_2.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 11,
    "title": "Mulgaon Residency",
    "cat": "Residential",
    "slug": "mulgaon-residency",
    "side": "L",
    "heroImage": "/project photos/photos and video/mulgaon/Bird Eye View_FV.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/mulgaon/Day View.jpg.jpeg",
      "/project photos/photos and video/mulgaon/Night View_A.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/mulgaon/Bird Eye View_FV.jpg.jpeg",
      "/project photos/photos and video/mulgaon/Day View.jpg.jpeg",
      "/project photos/photos and video/mulgaon/Night View_A.jpg.jpeg",
      "/project photos/photos and video/mulgaon/Worm Eye View.jpg (3).jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 12,
    "title": "New Narmada Satyam",
    "cat": "Residential",
    "slug": "new-narmada-satyam",
    "side": "R",
    "heroImage": "/project photos/photos and video/new narmada satyam/1.jpg",
    "gallery": [
      "/project photos/photos and video/new narmada satyam/2.jpg",
      "/project photos/photos and video/new narmada satyam/Bird Eye View A _01.jpg.jpeg",
      "/project photos/photos and video/new narmada satyam/WhatsApp Image 2025-03-10 at 9.05.14 AM.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/new narmada satyam/1.jpg",
      "/project photos/photos and video/new narmada satyam/2.jpg",
      "/project photos/photos and video/new narmada satyam/Bird Eye View A _01.jpg.jpeg",
      "/project photos/photos and video/new narmada satyam/WhatsApp Image 2025-03-10 at 9.05.14 AM.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 13,
    "title": "Shani Mandir Plaza",
    "cat": "Commercial",
    "slug": "shani-mandir-plaza",
    "side": "L",
    "heroImage": "/project photos/photos and video/shani mandir/09.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/shani mandir/12.jpg.jpeg",
      "/project photos/photos and video/shani mandir/bird eye view01.jpg.jpeg",
      "/project photos/photos and video/shani mandir/day.jpg.jpeg",
      "/project photos/photos and video/shani mandir/top terrace.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/shani mandir/09.jpg.jpeg",
      "/project photos/photos and video/shani mandir/12.jpg.jpeg",
      "/project photos/photos and video/shani mandir/bird eye view01.jpg.jpeg",
      "/project photos/photos and video/shani mandir/day.jpg.jpeg",
      "/project photos/photos and video/shani mandir/top terrace.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 14,
    "title": "Vishal View",
    "cat": "Residential",
    "slug": "vishal-view",
    "side": "R",
    "heroImage": "/project photos/photos and video/vishal view/Back Side View (1).jpg (1).jpeg",
    "gallery": [
      "/project photos/photos and video/vishal view/Vikas cam 01.jpg.jpeg",
      "/project photos/photos and video/vishal view/night View.jpg (1).jpeg",
      "/project photos/photos and video/vishal view/vishal bird eye view.jpg.jpeg",
      "/project photos/photos and video/vishal view/worm Eye View.jpg (1).jpeg"
    ],
    "images": [
      "/project photos/photos and video/vishal view/Back Side View (1).jpg (1).jpeg",
      "/project photos/photos and video/vishal view/Vikas cam 01.jpg.jpeg",
      "/project photos/photos and video/vishal view/night View.jpg (1).jpeg",
      "/project photos/photos and video/vishal view/vishal bird eye view.jpg.jpeg",
      "/project photos/photos and video/vishal view/worm Eye View.jpg (1).jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 15,
    "title": "Yashawant Kasturi",
    "cat": "Residential",
    "slug": "yashawant-kasturi",
    "side": "L",
    "heroImage": "/project photos/photos and video/yashawant kasturi/Back Side View B.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/yashawant kasturi/Bird Eye View Night_01.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Day view_A__02.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Night View A.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Bird Eye View Night_01.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/yashawant kasturi/Back Side View B.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Bird Eye View Night_01.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Day view_A__02.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Night View A.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 16,
    "title": "Narangi Residency",
    "cat": "Residential",
    "slug": "narangi-residency",
    "side": "R",
    "heroImage": "/project photos/photos and video/Renders Images/naringi 2/Back Side View_Narangi.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/Renders Images/naringi 2/IMG_1366.JPG.jpeg",
      "/project photos/photos and video/Renders Images/naringi 2/IMG_1367.JPG.jpeg"
    ],
    "images": [
      "/project photos/photos and video/Renders Images/naringi 2/Back Side View_Narangi.jpg.jpeg",
      "/project photos/photos and video/Renders Images/naringi 2/IMG_1366.JPG.jpeg",
      "/project photos/photos and video/Renders Images/naringi 2/IMG_1367.JPG.jpeg",
      "/project photos/photos and video/Renders Images/naringi 2/IMG_1368.JPG.jpeg",
      "/project photos/photos and video/Renders Images/naringi 2/IMG_1369.JPG.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed"
  },
  {
    "id": 17,
    "title": "Chandresh Heights",
    "cat": "Residential",
    "slug": "chandresh-heights",
    "side": "L",
    "heroImage": "/project photos/photos and video/chandresh /3.jpg",
    "gallery": [
      "/project photos/photos and video/chandresh /6.jpg",
      "/project photos/photos and video/chandresh /1.jpg"
    ],
    "images": [
      "/project photos/photos and video/chandresh /1.jpg",
      "/project photos/photos and video/chandresh /3.jpg",
      "/project photos/photos and video/chandresh /6.jpg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  },
  {
    "id": 18,
    "title": "New Narmada Satyam",
    "cat": "Residential",
    "slug": "new-narmada-satyam",
    "side": "R",
    "heroImage": "/project photos/photos and video/new narmada satyam/1.jpg",
    "gallery": [
      "/project photos/photos and video/new narmada satyam/2.jpg",
      "/project photos/photos and video/new narmada satyam/Bird Eye View A _01.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/new narmada satyam/1.jpg",
      "/project photos/photos and video/new narmada satyam/2.jpg",
      "/project photos/photos and video/new narmada satyam/Bird Eye View A _01.jpg.jpeg",
      "/project photos/photos and video/new narmada satyam/WhatsApp Image 2025-03-10 at 9.05.14 AM.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  },
  {
    "id": 19,
    "title": "IDBI Corporate Suites",
    "cat": "Corporate",
    "slug": "idbi-corporate-suites",
    "side": "L",
    "heroImage": "/project photos/photos and video/idbi/idbi day.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/idbi/worm eye view render copy.jpg.jpeg",
      "/project photos/photos and video/idbi/Night View 02_A.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/idbi/Bird Eye View.jpg (1).jpeg",
      "/project photos/photos and video/idbi/Night View 02_A.jpg.jpeg",
      "/project photos/photos and video/idbi/Night View.jpg.jpeg",
      "/project photos/photos and video/idbi/idbi day.jpg.jpeg",
      "/project photos/photos and video/idbi/worm eye view render copy.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  },
  {
    "id": 20,
    "title": "Yashawant Kasturi",
    "cat": "Residential",
    "slug": "yashawant-kasturi",
    "side": "R",
    "heroImage": "/project photos/photos and video/yashawant kasturi/Back Side View B.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/yashawant kasturi/Day view_A__02.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Night View A.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Back Side View B.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/yashawant kasturi/Back Side View B.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Bird Eye View Night_01.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Day view_A__02.jpg.jpeg",
      "/project photos/photos and video/yashawant kasturi/Night View A.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  },
  {
    "id": 21,
    "title": "Parnaka Plaza",
    "cat": "Residential",
    "slug": "parnaka-plaza",
    "side": "L",
    "heroImage": "/project photos/photos and video/Parnaka/6.jpg",
    "gallery": [
      "/project photos/photos and video/Parnaka/7.jpg",
      "/project photos/photos and video/Parnaka/8.jpg",
      "/project photos/photos and video/Parnaka/9.jpg"
    ],
    "images": [
      "/project photos/photos and video/Parnaka/1.jpg",
      "/project photos/photos and video/Parnaka/10.jpg",
      "/project photos/photos and video/Parnaka/2.jpg",
      "/project photos/photos and video/Parnaka/3.jpg",
      "/project photos/photos and video/Parnaka/4.jpg",
      "/project photos/photos and video/Parnaka/5.jpg",
      "/project photos/photos and video/Parnaka/6.jpg",
      "/project photos/photos and video/Parnaka/7.jpg",
      "/project photos/photos and video/Parnaka/8.jpg",
      "/project photos/photos and video/Parnaka/9.jpg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.05.14.jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.16.51 (1).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.16.51 (2).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.16.51.jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.01 (1).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.01.jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.28 (1).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.28 (2).jpeg",
      "/project photos/photos and video/Parnaka/WhatsApp Image 2026-03-24 at 13.48.28.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  },
  {
    "id": 22,
    "title": "Arunoday",
    "cat": "Residential",
    "slug": "arunoday",
    "side": "R",
    "heroImage": "/project photos/photos and video/Arunoday/arunoday 1/2.jpg",
    "gallery": [
      "/project photos/photos and video/Arunoday/arunoday 1/Scene 179(1).png",
      "/project photos/photos and video/Arunoday/arunoday 1/1.jpg"
    ],
    "images": [
      "/project photos/photos and video/Arunoday/arunoday 1/1.jpg",
      "/project photos/photos and video/Arunoday/arunoday 1/2.jpg",
      "/project photos/photos and video/Arunoday/arunoday 1/Scene 179(1).png"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  },
  {
    "id": 23,
    "title": "Mulgaon",
    "cat": "Residential",
    "slug": "mulgaon",
    "side": "L",
    "heroImage": "/project photos/photos and video/mulgaon/Worm Eye View.jpg (3).jpeg",
    "gallery": [
      "/project photos/photos and video/mulgaon/Day View.jpg.jpeg",
      "/project photos/photos and video/mulgaon/Night View_A.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/mulgaon/Bird Eye View_FV.jpg.jpeg",
      "/project photos/photos and video/mulgaon/Day View.jpg.jpeg",
      "/project photos/photos and video/mulgaon/Night View_A.jpg.jpeg",
      "/project photos/photos and video/mulgaon/Worm Eye View.jpg (3).jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  },
  {
    "id": 24,
    "title": "Happy Villa",
    "cat": "Residential",
    "slug": "happy-villa",
    "side": "R",
    "heroImage": "/project photos/photos and video/happy villa/draft 03.jpg.jpeg",
    "gallery": [
      "/project photos/photos and video/happy villa/DAY CAM 01.jpg.jpeg",
      "/project photos/photos and video/happy villa/EVE.jpg.jpeg"
    ],
    "images": [
      "/project photos/photos and video/happy villa/Bird Eye View A.jpg.jpeg",
      "/project photos/photos and video/happy villa/DAY CAM 01.jpg.jpeg",
      "/project photos/photos and video/happy villa/EVE.jpg.jpeg",
      "/project photos/photos and video/happy villa/draft 03.jpg.jpeg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  },
  {
    "id": 25,
    "title": "Gurudarshan",
    "cat": "Residential",
    "slug": "gurudarshan",
    "side": "L",
    "heroImage": "/project photos/photos and video/Gurudarshan/guru/2.jpg",
    "gallery": [
      "/project photos/photos and video/Gurudarshan/guru/3.jpg",
      "/project photos/photos and video/Gurudarshan/guru/1.jpg"
    ],
    "images": [
      "/project photos/photos and video/Gurudarshan/guru/1.jpg",
      "/project photos/photos and video/Gurudarshan/guru/2.jpg",
      "/project photos/photos and video/Gurudarshan/guru/3.jpg"
    ],
    "location": "Mumbai, India",
    "year": "2024",
    "area": "15,000 sq.ft",
    "status": "Completed",
    "isComingSoon": true
  }
];
